In [11]:
# Importing all basic dependencies
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
sns.set_theme(context='notebook', style='darkgrid',palette='dark', font_scale=1.2)
%matplotlib inline

In [12]:
# pip install scikit-learn  -> for installation
from sklearn.datasets import load_iris # -> loading iris dataset 

In [31]:
# getting an instance of the dataset
iris=load_iris()
iris.keys()

# -------- Keys and their Mapping --------------->
# Data->Input Data                                                                          # target->Output Data
# target_name->All differen possible outputs and their mapping                              # feature_name->Column-name

dict_keys(['data', 'target', 'frame', 'target_names', 'DESCR', 'feature_names', 'filename'])

In [14]:
# Creating pandas Dataframe from iris instance
df = pd.DataFrame(iris.data, columns=iris.feature_names)
df.head()


sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                5.1               3.5                1.4               0.2
1                4.9               3.0                1.4               0.2
2                4.7               3.2                1.3               0.2
3                4.6               3.1                1.5               0.2
4                5.0               3.6                1.4               0.2

In [32]:
# This directly helps us in diving our data into input and output dataset
X,y=load_iris(return_X_y=True)
print(f"X\n{X[:10]}\n\nY:\n{y[:10]}")

# The above things can be achieved by --> 
    # iris = load_iris()
    # X,y=iris.data,iris.target

X
[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.  3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]]

Y:
[0 0 0 0 0 0 0 0 0 0]


In [21]:
# Divinding Data for Training and Testing purposes
from sklearn.model_selection import train_test_split


# test-size denote what percentage of data to be use for setting
# random_state=is use to seed it with a particular value in order to generate same result every time we run with this state
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=3)
print(f"X_train:{X_train.shape}")
print(f"X_test:{X_test.shape}")
print(f"y_train:{y_train.shape}")
print(f"y_test:{y_test.shape}")

X_train:(120, 4)
X_test:(30, 4)
y_train:(120,)
y_test:(30,)


In [26]:
# Here data points have different scale and it is import to normalize them for better prediction and this is done by computing z-score
#  but sk-learn provide function that help us do that in a simple ease using Scaler objects
# Scaling and Normalisation make sure that mean of data points in 0 and Std is 1 (But std is priortized over mean) 
print("Standard-Devviation: ", X_train.std())

1.9673832447180244

In [28]:
# Scalling Data to same scale

from sklearn.preprocessing import StandardScaler
# from sklearn.preprocessing import MinMaxScaler # ->other type of scaller

scaler=StandardScaler()

# Making model learn
scaler.fit(X_train)

scalled_X=scaler.transform(X_train)
print("Standard-Devviation: ", scalled_X.std())

# -------- OR ---------
# scalled_X=scaler.fit_transform(X_train) # -> fit and train in 1 single step


Standard-Devviation:  1.0


` Now Use Diffrent Models to train your ML algos like linear-regression,KNN,svm etc.. `