In [2]:
import pandas as pd

In [3]:
with open("Iris_dataset.csv") as Iris_dataset:
    iris=pd.read_csv(Iris_dataset)
iris.head()

Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0   1            5.1           3.5            1.4           0.2  Iris-setosa
1   2            4.9           3.0            1.4           0.2  Iris-setosa
2   3            4.7           3.2            1.3           0.2  Iris-setosa
3   4            4.6           3.1            1.5           0.2  Iris-setosa
4   5            5.0           3.6            1.4           0.2  Iris-setosa

In [4]:
# drop(row-no)->return a new data frame with removal of passed row-no
iris.drop(0,inplace=True)
iris.head()

Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
1   2            4.9           3.0            1.4           0.2  Iris-setosa
2   3            4.7           3.2            1.3           0.2  Iris-setosa
3   4            4.6           3.1            1.5           0.2  Iris-setosa
4   5            5.0           3.6            1.4           0.2  Iris-setosa
5   6            5.4           3.9            1.7           0.4  Iris-setosa

In [5]:
# if we try droping the same row again it will throw an error as it work according to index and not position
iris.drop(0,inplace=True)
iris

# so drop() ->remove the row but not reset the indexing

KeyError: '[0] not found in axis'

In [6]:
# To know all indexes u have u can use ->index
iris.drop(3,inplace=True)
print(iris.index) # so u will not have to 0 & 3 as u dropped it

Int64Index([  1,   2,   4,   5,   6,   7,   8,   9,  10,  11,
            ...
            140, 141, 142, 143, 144, 145, 146, 147, 148, 149],
           dtype='int64', length=148)


In [7]:
# U can chk what index is at pos 'k' -> df.index[k]
print(iris.index[3])

5


In [8]:
iris.head()

Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
1   2            4.9           3.0            1.4           0.2  Iris-setosa
2   3            4.7           3.2            1.3           0.2  Iris-setosa
4   5            5.0           3.6            1.4           0.2  Iris-setosa
5   6            5.4           3.9            1.7           0.4  Iris-setosa
6   7            4.6           3.4            1.4           0.3  Iris-setosa

In [9]:
# Now using index we can drop row at a particular pos also
iris.drop(iris.index[3],inplace=True)
iris.head()

Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
1   2            4.9           3.0            1.4           0.2  Iris-setosa
2   3            4.7           3.2            1.3           0.2  Iris-setosa
4   5            5.0           3.6            1.4           0.2  Iris-setosa
6   7            4.6           3.4            1.4           0.3  Iris-setosa
7   8            5.0           3.4            1.5           0.2  Iris-setosa

In [10]:
# can drop multiple rows also
iris.drop(iris.index[[0,2,4]],inplace=True)
iris

Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm  \
2      3            4.7           3.2            1.3           0.2   
6      7            4.6           3.4            1.4           0.3   
8      9            4.4           2.9            1.4           0.2   
9     10            4.9           3.1            1.5           0.1   
10    11            5.4           3.7            1.5           0.2   
..   ...            ...           ...            ...           ...   
145  146            6.7           3.0            5.2           2.3   
146  147            6.3           2.5            5.0           1.9   
147  148            6.5           3.0            5.2           2.0   
148  149            6.2           3.4            5.4           2.3   
149  150            5.9           3.0            5.1           1.8   

            Species  
2       Iris-setosa  
6       Iris-setosa  
8       Iris-setosa  
9       Iris-setosa  
10      Iris-setosa  
..              ...  
145  Iris-virginica  
146  Iris-virginica  
147  Iris-virginica  
148  Iris-virginica  
149  Iris-virginica  

[144 rows x 6 columns]

In [11]:
print(iris.Species=='Iris-setosa')

print("\n\n~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~\n\n")

print(iris[iris.Species=='Iris-setosa'][:10])

print("\n\n~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~\n\n")
iris[iris.Species=='Iris-setosa'].describe()

2       True
6       True
8       True
9       True
10      True
       ...  
145    False
146    False
147    False
148    False
149    False
Name: Species, Length: 144, dtype: bool


~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~


    Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
2    3            4.7           3.2            1.3           0.2  Iris-setosa
6    7            4.6           3.4            1.4           0.3  Iris-setosa
8    9            4.4           2.9            1.4           0.2  Iris-setosa
9   10            4.9           3.1            1.5           0.1  Iris-setosa
10  11            5.4           3.7            1.5           0.2  Iris-setosa
11  12            4.8           3.4            1.6           0.2  Iris-setosa
12  13            4.8           3.0            1.4           0.1  Iris-setosa
13  14            4.3           3.0            1.1           0.1  Iris-setosa
14  15            5.8           4.0      

Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm
count  44.000000      44.000000     44.000000      44.000000     44.000000
mean   28.386364       5.006818      3.418182       1.461364      0.245455
std    13.051269       0.365614      0.390749       0.180717      0.110925
min     3.000000       4.300000      2.300000       1.000000      0.100000
25%    17.750000       4.800000      3.175000       1.375000      0.200000
50%    28.500000       5.000000      3.400000       1.500000      0.200000
75%    39.250000       5.200000      3.700000       1.600000      0.300000
max    50.000000       5.800000      4.400000       1.900000      0.600000

In [12]:
# NOTE-> iloc work on position and not on indexes....Will explain in Advance Pandas NOTEBOOK

print(iris.head())

print("~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~")

print(iris.iloc[0]) #it will give data of index viz on very top as use position for accessing data

    Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
2    3            4.7           3.2            1.3           0.2  Iris-setosa
6    7            4.6           3.4            1.4           0.3  Iris-setosa
8    9            4.4           2.9            1.4           0.2  Iris-setosa
9   10            4.9           3.1            1.5           0.1  Iris-setosa
10  11            5.4           3.7            1.5           0.2  Iris-setosa
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Id                         3
SepalLengthCm            4.7
SepalWidthCm             3.2
PetalLengthCm            1.3
PetalWidthCm             0.2
Species          Iris-setosa
Name: 2, dtype: object


In [13]:
# loc is similar to iloc but it work according to index and not the position of data in data-frame
print(iris.loc[2])

Id                         3
SepalLengthCm            4.7
SepalWidthCm             3.2
PetalLengthCm            1.3
PetalWidthCm             0.2
Species          Iris-setosa
Name: 2, dtype: object


In [14]:
iris.tail()

Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm  \
145  146            6.7           3.0            5.2           2.3   
146  147            6.3           2.5            5.0           1.9   
147  148            6.5           3.0            5.2           2.0   
148  149            6.2           3.4            5.4           2.3   
149  150            5.9           3.0            5.1           1.8   

            Species  
145  Iris-virginica  
146  Iris-virginica  
147  Iris-virginica  
148  Iris-virginica  
149  Iris-virginica

In [15]:
# We can use loc method to add a row at very end of your data-frame
iris.loc[0]=[1,2,3.3,5,4,"Iris-setosa"]
iris.tail()

Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm  \
146  147            6.3           2.5            5.0           1.9   
147  148            6.5           3.0            5.2           2.0   
148  149            6.2           3.4            5.4           2.3   
149  150            5.9           3.0            5.1           1.8   
0      1            2.0           3.3            5.0           4.0   

            Species  
146  Iris-virginica  
147  Iris-virginica  
148  Iris-virginica  
149  Iris-virginica  
0       Iris-setosa

In [16]:
temp=iris.copy()
temp.head()

Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
2    3            4.7           3.2            1.3           0.2  Iris-setosa
6    7            4.6           3.4            1.4           0.3  Iris-setosa
8    9            4.4           2.9            1.4           0.2  Iris-setosa
9   10            4.9           3.1            1.5           0.1  Iris-setosa
10  11            5.4           3.7            1.5           0.2  Iris-setosa

In [17]:
# reset_index()-> Use to rest index and provide increasing order. Return a new data-frame if need to do it inplace make inplace=True
temp.reset_index()

index   Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm  \
0        2    3            4.7           3.2            1.3           0.2   
1        6    7            4.6           3.4            1.4           0.3   
2        8    9            4.4           2.9            1.4           0.2   
3        9   10            4.9           3.1            1.5           0.1   
4       10   11            5.4           3.7            1.5           0.2   
..     ...  ...            ...           ...            ...           ...   
140    146  147            6.3           2.5            5.0           1.9   
141    147  148            6.5           3.0            5.2           2.0   
142    148  149            6.2           3.4            5.4           2.3   
143    149  150            5.9           3.0            5.1           1.8   
144      0    1            2.0           3.3            5.0           4.0   

            Species  
0       Iris-setosa  
1       Iris-setosa  
2       Iris-setosa  
3       Iris-setosa  
4       Iris-setosa  
..              ...  
140  Iris-virginica  
141  Iris-virginica  
142  Iris-virginica  
143  Iris-virginica  
144     Iris-setosa  

[145 rows x 7 columns]

In [18]:
# Note how reset_index() store previous index in index col sepreately if we don't want that drop it
temp.reset_index(drop=True,inplace=True)
print(temp.index)
temp.head()

RangeIndex(start=0, stop=145, step=1)


Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0   3            4.7           3.2            1.3           0.2  Iris-setosa
1   7            4.6           3.4            1.4           0.3  Iris-setosa
2   9            4.4           2.9            1.4           0.2  Iris-setosa
3  10            4.9           3.1            1.5           0.1  Iris-setosa
4  11            5.4           3.7            1.5           0.2  Iris-setosa

In [19]:
temp.head()

Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0   3            4.7           3.2            1.3           0.2  Iris-setosa
1   7            4.6           3.4            1.4           0.3  Iris-setosa
2   9            4.4           2.9            1.4           0.2  Iris-setosa
3  10            4.9           3.1            1.5           0.1  Iris-setosa
4  11            5.4           3.7            1.5           0.2  Iris-setosa

In [20]:
# If we need to remove a column we can use drop() but provide axis=1(stands for column)
temp.drop('SepalLengthCm',axis=1,inplace=True)
temp.head()

Id  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0   3           3.2            1.3           0.2  Iris-setosa
1   7           3.4            1.4           0.3  Iris-setosa
2   9           2.9            1.4           0.2  Iris-setosa
3  10           3.1            1.5           0.1  Iris-setosa
4  11           3.7            1.5           0.2  Iris-setosa

In [21]:
del temp['PetalWidthCm']
temp.head()

Id  SepalWidthCm  PetalLengthCm      Species
0   3           3.2            1.3  Iris-setosa
1   7           3.4            1.4  Iris-setosa
2   9           2.9            1.4  Iris-setosa
3  10           3.1            1.5  Iris-setosa
4  11           3.7            1.5  Iris-setosa

In [22]:
temp=iris.copy()
temp.head()

Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
2    3            4.7           3.2            1.3           0.2  Iris-setosa
6    7            4.6           3.4            1.4           0.3  Iris-setosa
8    9            4.4           2.9            1.4           0.2  Iris-setosa
9   10            4.9           3.1            1.5           0.1  Iris-setosa
10  11            5.4           3.7            1.5           0.2  Iris-setosa

In [23]:
# Let say I want a add a column with val = SepLen-PetLen
temp['sepLen-petLen(cm)']=temp['SepalLengthCm']-temp['PetalLengthCm']
temp.head()

Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species  \
2    3            4.7           3.2            1.3           0.2  Iris-setosa   
6    7            4.6           3.4            1.4           0.3  Iris-setosa   
8    9            4.4           2.9            1.4           0.2  Iris-setosa   
9   10            4.9           3.1            1.5           0.1  Iris-setosa   
10  11            5.4           3.7            1.5           0.2  Iris-setosa   

    sepLen-petLen(cm)  
2                 3.4  
6                 3.2  
8                 3.0  
9                 3.4  
10                3.9

In [24]:
# If we want to add a column with all val=k
temp["Arbtry_col"]=1
temp.head()

Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species  \
2    3            4.7           3.2            1.3           0.2  Iris-setosa   
6    7            4.6           3.4            1.4           0.3  Iris-setosa   
8    9            4.4           2.9            1.4           0.2  Iris-setosa   
9   10            4.9           3.1            1.5           0.1  Iris-setosa   
10  11            5.4           3.7            1.5           0.2  Iris-setosa   

    sepLen-petLen(cm)  Arbtry_col  
2                 3.4           1  
6                 3.2           1  
8                 3.0           1  
9                 3.4           1  
10                3.9           1

In [26]:
# Want to add num from 1-n
print(temp.shape)
temp['Arbtry_col2']=[i for i in range(temp.shape[0])]
temp.head()

(145, 9)


Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species  \
2    3            4.7           3.2            1.3           0.2  Iris-setosa   
6    7            4.6           3.4            1.4           0.3  Iris-setosa   
8    9            4.4           2.9            1.4           0.2  Iris-setosa   
9   10            4.9           3.1            1.5           0.1  Iris-setosa   
10  11            5.4           3.7            1.5           0.2  Iris-setosa   

    sepLen-petLen(cm)  Arbtry_col  Arbtry_col2  
2                 3.4           1            0  
6                 3.2           1            1  
8                 3.0           1            2  
9                 3.4           1            3  
10                3.9           1            4

Some IMP Functions

In [29]:
# value_counts() -> return count of each distinct value
temp['Species'].value_counts()

Iris-versicolor    50
Iris-virginica     50
Iris-setosa        45
Name: Species, dtype: int64

In [30]:
# unique()-> return all unique ele in a column
temp.Species.unique()

array(['Iris-setosa', 'Iris-versicolor', 'Iris-virginica'], dtype=object)

Converting dataFrame to some file like CSV

In [35]:
import numpy as np
dfrm=pd.DataFrame(np.arange(20).reshape(4,5),columns=np.array(["Column-"+str(i) for i in range(5)]),index=np.array([i for i in range(4)]))

dfrm

Column-0  Column-1  Column-2  Column-3  Column-4
0         0         1         2         3         4
1         5         6         7         8         9
2        10        11        12        13        14
3        15        16        17        18        19

In [36]:
# Change our dataFrame to csv 
dfrm.to_csv('my Data-Frame.csv')

# can change to xl,csv etc..

DataFrame to Array

In [40]:
# Select all required values using iloc -> use .values to get ther value in a array format
array=dfrm.iloc[:].values
print(array)

print("\n\n")

# Select all required values using loc -> use .values to get ther value in a array format
array2=dfrm.loc[:].values
print(array2)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]



[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]


In [41]:
# Can convert a part to array also
array3=dfrm.iloc[2:,1:4]
print(array3)

   Column-1  Column-2  Column-3
2        11        12        13
3        16        17        18


In [43]:
# info()->provide some import looks of dataframe
temp.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 145 entries, 2 to 0
Data columns (total 9 columns):
 #   Column             Non-Null Count  Dtype  
---  ------             --------------  -----  
 0   Id                 145 non-null    int64  
 1   SepalLengthCm      145 non-null    float64
 2   SepalWidthCm       145 non-null    float64
 3   PetalLengthCm      145 non-null    float64
 4   PetalWidthCm       145 non-null    float64
 5   Species            145 non-null    object 
 6   sepLen-petLen(cm)  145 non-null    float64
 7   Arbtry_col         145 non-null    int64  
 8   Arbtry_col2        145 non-null    int64  
dtypes: float64(5), int64(3), object(1)
memory usage: 11.3+ KB
